[window]
decorations = "none"
padding = { x = 18, y = 14 }
opacity = 0.7

[font]
size = 11.0

[colors]

[colors.primary]
background = "#16141f"
foreground = "#eaeaef"

[colors.cursor]
text = "#2b2d31"
cursor = "#EAEAEF"

[colors.normal]
black   = "#2b2d31"
red     = "#ef5d67"
green   = "#8edb73"
yellow  = "#f7c553"
blue    = "#86aaf9"
magenta = "#e29ef3"
cyan    = "#EAEAEF"
white   = "#f8f8fa"

[colors.bright]
black   = "#505258"
red     = "#ff7680"
green   = "#a2ee8b"
yellow  = "#ffd86f"
blue    = "#97b6ff"
magenta = "#efb5f9"
cyan    = "#94e8e3"
white   = "#ffffff"

[colors.selection]
text = "#2b2d31"
background = "#b2c3ff"

[colors.vi_mode_cursor]
text   = "#2b2d31"
cursor = "#bfc6ff"
